Первый PR
K1ngNothing/3D-Render-from-Scratch pull request #1
Opened 2024-01-17 20:38 UTC by K1ngNothing

На данный момент имплементировал только растеризацию. Пока что написан чудесный говнокод -- так и задумано, как минимум в течение января собираюсь активно работать над проектом. Так что можешь не спешить смотреть PR, будет еще много доработок. Более подробно написал в телеграмме.

2024-02-05 18:48 UTC, DimaTrushin requested changes
Обрати внимание, что я не повторял замечания. Если одна и та же ошибка всречалась несколько раз, я комментировал лишь единожды. Потому я ожидаю, что ты поправишь все аналогичные замечания всюду.

У тебя есть несколько проблем с общим дизайном. У тебя перемешаны роли объектов. Я постарался указать на это.

Так же у тебя не хватает классов и их методов для работы с данными. Это все вырастает в большое неудобство и количество костылей для работы с кодом.

И еще. Ты всегда векторы передаешь по значению. Это огромное количество копирования кругом. Я думаю, что это остновная проблема твоей производительности.

2024-02-05 18:48 UTC, DimaTrushin commented on main.cpp
> +    app.addObjects({triangle1});
Нарушение уровня абстракции. Application ничего не должен знать про объекты и сцену. Это не его обязанность. Тут должно быть лишь следующее:
```cpp
#include "Application.h"
#include "Except.h"

int main() {
  try {
    Application app;
    app.run();
  } catch(...) {
    except::react();
  }
  return 0;
}
Except.h
namespace except {
void react();
}
Except.cpp
#include "Except.h"

namespace except {
void react() {
  try {
    throw;
  } catch(std::exception& e) {
    // обрабатываешь известные исключения
  } catch(...) {
    // обрабатываешь незивестные исключения
  }
}
}
```
Так как ты не отключил exception, то обязательно надо не пропустить их в Os.

Есть текст по созданию треугольника должен быть исполнен где-то в конструкторе Application.

2024-02-05 18:48 UTC, DimaTrushin commented on main.cpp
> +    using namespace application;
Сделай нормальное название для namespace, а не просто application.

2024-02-05 18:48 UTC, DimaTrushin commented on src/application.h
> +    void addObjects(std::vector<Triangle> triangles, Point3d position = Point3d::Zero());
1) Этому методу не место в Application.
2) Никогда не принимай вектор by value!

2024-02-05 18:48 UTC, DimaTrushin commented on src/application.h
> +    static constexpr double far_plane_dist = 10.0;
Вот это выглядит слишком специфично. Про это уже не должно знать приложение.

2024-02-05 18:48 UTC, DimaTrushin commented on src/application.h
> +    static constexpr char window_name[] = "3D Renderer from Scratch";
Ко всем константам добавь префикс k_ иначе не понятно, что это статические константы, их хер отличишь от переменных.

2024-02-05 18:48 UTC, DimaTrushin commented on src/application.h
> +    void displayImage();
Очень плохо спроектировано. У тебя совершенно не видно, как текут данные. Но я погляжу еще внутри, что происходит. Когда функция ничего не принимает и ничего не возвращает, это худший вид не pure функции. Она только контролирует глобальное состояние ничего не говоря о том, как именно она это делает. Внутри нее все со всем в любой момент времени взаимодействует. Такой стиль ничем не лучше глобальных переменных и глобальных функций. Ты просто проблему перенес внутрь Application.

2024-02-05 18:48 UTC, DimaTrushin commented on src/application.h
> +#include <math.h>
не думаю, что этому инклуду тут место.

2024-02-05 18:48 UTC, DimaTrushin commented on src/application.cpp
> +      camera_(near_plane_dist, far_plane_dist, fov_angle, aspect_ratio) {
1) Мы точно хотим эти параметры тут настраивать?
2) Ты задал все поля кроме world. Вопрос, а зачем ты создание world вынес за пределы конструктора Application? Сделай нормальный конструктор для world.

2024-02-05 18:48 UTC, DimaTrushin commented on src/application.cpp
> +void Application::checkEvents() {
Плохое название, это не checkEvents, а handleAllEvents или dispatchAllEvents.

2024-02-05 18:48 UTC, DimaTrushin commented on src/application.cpp
> +            exit(0);
А ты уверен, что это так надо завершать? Я бы сделал return в этом месте. И уже внешний цикл в event loop остановится.

2024-02-05 18:48 UTC, DimaTrushin commented on src/application.cpp
> +    displayImage();
Мне не нравится такой подход. Эти два действия выглядят не как глобальные действия, которые имеют смысл до event loop-а, а как локальные действия, которые запускаются на какие-то события в event loop. Например, у тебя есть событие посвященное открытию окна. В общем, это плохой дизайн. Убрать это отсюда.

2024-02-05 18:48 UTC, DimaTrushin commented on src/application.cpp
> +    renderer_.clear();
Дерьмовый интерфейс. С чего вдруг мне как пользователю renderer звать метод clear? Это же не буфер, это объект, который берет камеру, мир и отрисовывает мне экран. Я бы ожидал такой вызов
```cpp
screen_ = renderer_.render(camera_, world_);
```
И все. Эта вся низкоуровневая работа не для Application. Ты пытаешься будучи генеральным директором объяснять, как расскладывать вилки на столе. Это не обязанность Application. Ошибка уровня абстракции.

2024-02-05 18:48 UTC, DimaTrushin commented on src/application.cpp
> +    render_window_.display();
Вот это супер запутывает. Я вот смотрю сюда и у меня полное недопонимание, какого хрена!? А как отрисовывается картинка? Данные о ней ниоткуда не поступили, что происходит непонятно.
1) Как я пониманю, название метода нагло врет. Этот метод -- это displayWindow, а не displayImage. Потому стоит начать с этого.
2) Если уж рисовать картинку, то я бы ожидал чего-то такого
```cpp
displayScreen(screen_);
// или
renderer_window_.display(screen_);
```

2024-02-05 18:48 UTC, DimaTrushin commented on src/world.h
> +    void addObjects(std::vector<Triangle> triangles, Point3d position);
Сигнатура! Никогда не принимай вектор или конкретный контейнер по значению. Можно уж тогда итераторы передавать в крайнем случае.

2024-02-05 18:48 UTC, DimaTrushin commented on src/world.h
> +    std::vector<Triangle> getTriangles() const;
Плохая идея возвращать вектор треугольников by value. World должен хранить данные внутри в нужном для отрисовки формате. Нахрена тогда он нужен, если ты все налету строишь и ничего не хранишь как следует. Где тогда будут лежать данные в правильном формате?

2024-02-05 18:48 UTC, DimaTrushin commented on src/world.cpp
> +std::vector<Triangle> World::getTriangles() const {
Вместо этого лучше верни прокси объект, который знает как по нему пробежаться итераторами. Ровно для этого и была придумана идея итераторов, чтобы не возиться с конкретным контейнером.

2024-02-05 18:48 UTC, DimaTrushin commented on src/renderer.h
> +    std::vector<std::vector<sf::Color>> pixel_colors_;
НИКОГДА не используй вектор векторов. Если тебе нужен класс Screen, то напиши его. И внутри него сделай один std::vector с правильной индексацией. Все должено лежать в единой памяти непрерывно.

2024-02-05 18:48 UTC, DimaTrushin commented on src/renderer.h
> +    std::pair<size_t, size_t> getScreenSize() const;
Не используй std::pair, потому что пользователю не понятно, что значат first и second. Заведи struct с нужным именем и нужными названиями полей. И тогда пользователь сможет по нормальным названиям обращаться к элементам структуры.

2024-02-05 18:48 UTC, DimaTrushin commented on src/renderer.h
> +    void clear();
Плохая сигнатура. Renderer это высокоуровневый объект, его задача по камере и миру сделать пиксельный экран. Потому у него должен быть только один публичный метод make или что-то в этом духе вида
```cpp
Screen make(const Camera& camera, const World& world);
```
Ну или вместо World должен быть контейнер или итераторы на контейнер со всеми треугольниками или той информацией, которая тебе нужна для отрисовки.

2024-02-05 18:48 UTC, DimaTrushin commented on src/renderer.h
> +          z_buffer_(screen_w, std::vector<double>(screen_h, 1)) {
1) Сделай два класса Screen и ZBuffer и сделай для них нормальные дефолтные конструкторы.
2) У тебя тут идет волшебная константа. Если уберешь все в конструктор ZBuffer, как раз она исчезнет.

2024-02-05 18:48 UTC, DimaTrushin commented on src/renderer.cpp
> +void Renderer::clear() {
Убрать.

2024-02-05 18:48 UTC, DimaTrushin commented on src/renderer.h
> +    std::vector<std::vector<sf::Color>> pixel_colors_;
Не думаю, что надо хранить screen в renderer. А вот размеры пиксельного экрана и z_buffer хранить стоит. Либо ты строишь каждый раз новый screen. Либо передаешь в метод make или render уже аллоцированный экран, чтобы не делать новую аллокацию.

2024-02-05 18:48 UTC, DimaTrushin commented on src/renderer.cpp
> +    render_window.draw(&pixels[0], pixels.size(), sf::PrimitiveType::Points);
Ты в этой функции смешиваешь две разные задачи:
1) Создание экрана с пикселями.
2) Отрисовка с помощью GUI библиотеки.
Вот эту строчку надо вынести наружу и не renderer должен отрисовывать на GUI. Это НЕ его обязанность, а обязанность View объекта. Ну или Application в крайнем случае. Так как у тебя тут сложно в sfml выделить view объект отдельно от главного окна, которое в себе перемешивает все элементы дизайна с ног на голову.

2024-02-05 18:48 UTC, DimaTrushin commented on src/renderer.cpp
> +    std::vector<sf::Vertex> pixels;
Если делаешь кучу push_back-ов, то хотя бы сделай reserve для нужного размера перед циклом.

2024-02-05 18:48 UTC, DimaTrushin commented on src/renderer.cpp
> +            sf::Vector2f position{static_cast<float>(i), static_cast<float>(screen_h - j)};
1) static_cast явно в бизнес логике -- это ошибка дизайна. Это значит, у тебя не достаточно нужных классов, функций и интерфейсов для работы с данными.
2) У тебя на самом деле есть две системы координат: целочисленная на пиксельном экране и double на экране с double координатами. Потому тебе просто нужны функции конвертации между этими системами координат.
3) Я видел у тебя в другом месте используется double, тут используется float. Ты определись, что ты используешь и перейди к единому типу данных.

2024-02-05 18:48 UTC, DimaTrushin commented on src/renderer.cpp
> +            color.b *= shade_coeff;
Выглядит так, что тебе не хватает метода домножения color на коэффициент. Сделай внешний оператор operator*=. Ты можешь к чужому классу снаружи добавить такой оператор всегда. И сделай прокси хедер через который подключаешь sf::Color, а не  напрямую.

2024-02-05 18:48 UTC, DimaTrushin commented on src/renderer.cpp
> +            if (isPointInsideTriangle2D({double_x, double_y}, triangle) &&
4 вложенных scope даже в ядре Linux запрещено больше 3.

2024-02-05 18:48 UTC, DimaTrushin commented on src/renderer.cpp
> +    }
Вот это выглядит как отдельная функция, которая считает все переменные выше. Почему нельзя выделить это в функцию, которая вернет четверку double-ов?

2024-02-05 18:48 UTC, DimaTrushin commented on src/geometry.h
> +constexpr double EPS = 1e-9;
Не используй ВСЕКАПСОМ для названия переменных. Такой стиль используется только для макросов.

2024-02-05 18:48 UTC, DimaTrushin commented on src/geometry.cpp
> +    return (abs(actual_area - supposed_area) < EPS);
зачем внешние скобки?

2024-02-05 18:48 UTC, DimaTrushin commented on src/geometry.cpp
> +    };
Почему не выделил во вспомогательную функцию? Или это только тут нужно?

2024-02-05 18:48 UTC, DimaTrushin commented on src/geometry.cpp
> +Point2d get2dPoint(const Point3d& X) {
Это выглядит, как функция хелпер, которая должна лежать в публичном доступе. Неужели она тебе никогда не понадобится снаружи?

2024-02-05 18:48 UTC, DimaTrushin commented on src/object.cpp
> +        }
Вложенный цикл означает, что у тебя у треугольника не хватает метода +=

2024-02-05 18:48 UTC, DimaTrushin commented on src/object.cpp
> +    return triangles_;
плохо возвращать by value, лучше const reference

2024-02-05 18:48 UTC, DimaTrushin commented on src/camera.h
> +    Triangle transformTriangle(const Triangle& triangle) const;
А клиппинга у тебя пока нет? Просто у тебя так может порвать треугольник если ты не сделаешь клиппинг до этого преобразования. А с клиппингом у тебя может вернуться несколько треугольников.

2024-02-05 18:48 UTC, DimaTrushin commented on src/camera.cpp
> +void Camera::constructTransformMatrix() {
Лучше сделать этот метод возвращающим матрицу и вызывать в конструкторе в списке инициализации этот метод.

2024-02-05 18:48 UTC, DimaTrushin commented on src/camera.cpp
> +        assert(-1 - EPS <= point.x() && point.x() <= 1 + EPS && -1 - EPS <= point.y() &&
тут можно ввести метод is_in_range(point) и тогда в assert-е будет проще проверять условие.

2024-02-05 18:48 UTC, DimaTrushin commented on src/camera.cpp
> +    constructTransformMatrix();
старайся не делать такие вызовы, а писать в виде
```cpp
transform_mat_(constructTransformMatrix(...)) {}
```
и было бы лучше передавать явно в эту функцию все аргументы, а не надеяться, на инициализированные поля.

2024-03-13 21:57 UTC, K1ngNothing commented on src/camera.h
> +    Triangle transformTriangle(const Triangle& triangle) const;
На данный момент нет, про такую проблему в курсе

2024-03-13 21:57 UTC, K1ngNothing commented on src/geometry.cpp
> +    return (abs(actual_area - supposed_area) < EPS);
Какого-то философского смысла нет, просто я привык оборачивать булевые выражения в скобки. Наверно стоит убрать.

2024-03-13 21:57 UTC, K1ngNothing commented on src/application.cpp
> +    displayImage();
Эти действия сейчас вынесены из event loop-a из-за того, что пока что приложение выдает статичную картинку. Соответственно нет смысла каждый раз отрисовывать кадр заново. Эти действия вернутся в loop когда я начну парсить пользовательский ввод.

2024-03-13 21:57 UTC, K1ngNothing commented on src/world.h
> +    std::vector<Triangle> getTriangles() const;
У меня была идея хранить треугольники в объектах. Сделано это было для того, чтобы при трансформации объекта (например, повороте), мне не нужно было выискивать в общем контейнере те треугольники, что мне нужно изменить. Но при таком подходе при каждой отрисовке кадра у меня будут копироваться все треугольники всех объектов, что как будто не круто. С другой стороны, мне так и так понадобятся копии треугольников, т.к. я потом буду их всячески трансформировать при переходе в пространство камеры, так что может быть это и не так плохо.

EDIT: кажется твой комментарий про то, что следует заменить std::vector<Triangle> на контейнер с итераторами, отвечает на мои вопросы :)

2024-03-13 21:57 UTC, K1ngNothing commented on src/renderer.h
> +    std::vector<std::vector<sf::Color>> pixel_colors_;
А вообще получается каждый раз, когда мне захочется использовать двумерный массив, мне стоит писать свой кастомный контейнер с непрерывной памятью? Нет ли какого-то готового решения?

2024-03-13 21:57 UTC, K1ngNothing commented on src/renderer.h
> +    std::vector<std::vector<sf::Color>> pixel_colors_;
А точно ли стоит хранить z_buffer? Тогда при каждой отрисовке кадра мы должны не забывать его зачищать. Не проще ли тогда каждый раз создавать zBuffer заново, как это у меня сделано сейчас? Из минусов я вижу то, что мы на каждую отрисовку кадра делаем аллокацию screen_w * screen_h double + sf::Color, но в сравнении с самим алгоритмом ZBuffer-a это как будто не критично. Или я не прав?

2024-03-15 13:07 UTC, DimaTrushin requested changes

2024-03-15 13:07 UTC, DimaTrushin commented on src/world.h
> +    std::vector<Triangle> getTriangles() const;
Важно, чтобы было так. Если ты создаешь контейнер, то потом он:
1) не копируется
2) не реаллоцирует
То есть ты либо его передаешь по ссылке, либо муваешь. И все данные в нем меняешь inplace, но за этим надо следить! Я бы рекомендовал сделать свой вектор с запрещенными копирующими операциями вот так:
```cpp
template<class T>
class vector : public std::vector<T> {
public:
  using Base = public std::vector<T>;
  using Base::Base;
  vector(const vector&) = delete;
  vector(vector&&) noexcept = default;
  vector& operator=(const vector&) = delete;
  vector& operator=(vector&&) noexcept = default;
};
```
Тогда у тебя будет контейнер, который имеет интерфейс вектора, но ты нигде не пропустишь, что ты его случайно скопировал.

В целом подход с итераторами должен решить все проблемы.

2024-03-15 13:07 UTC, DimaTrushin commented on src/renderer.h
> +    std::vector<std::vector<sf::Color>> pixel_colors_;
Да, для многомерных массивов стоит всегда использовать непрерывный контейнер. Все библиотеки так внутри делают. Это связано с тем, что данные тогда кеш-френдли и префетчер-френдли.

Из говотых библиотек я думаю можно взять любую, которая реализует тензоры на плюсах. Из известных есть 
- xtensor --  https://github.com/xtensor-stack/xtensor
- Еще Eigen умеет в многомерные массивы, но у них это пока не stable фича.
- Есть еще backend для tensorflow.

2024-03-15 13:07 UTC, DimaTrushin commented on src/renderer.h
> +    std::vector<std::vector<sf::Color>> pixel_colors_;
По-хорошему надо создавать объекты по мере необходимости локально там, где надо. И если ты видишь, что производительность требует преаллокации, то ее надо выполнять. И да, при преаллокации у тебя появляется забота о том, чтобы чистить данные перед вызовом. Но это добавление одной строчки в начале функции, которая делает отрисовку. Сделать одну чистку все равно быстрее аллокации. Другое дело, на сколько есть выигрышь от преаллокации, это уже надо тестировать.

А если ты создаешь налету z-буффер, то непонятно зачем ты хранишь пиксельный экран? Ты нарушаешь локальность и заодно хранишь внутри себя данное, которое имеет смысл только во время вызова функции отрисовки, да еще и берешь на себя ответственность за владение этими данными. Так что в любом случае хранить тут этот экран не стоит.

2024-03-15 13:07 UTC, DimaTrushin commented on src/geometry.cpp
> +    return (abs(actual_area - supposed_area) < EPS);
На самом деле это очень плохая привычка оборачивать выражения в скобки. Есть ситуации, когда это может поменять тип выражения. А так как C++ ведет себя по разному в зависимости от получающегося типа выражения, это может привести к совершенно непредсказуемым последствиям. Потому стоит ставить обрамляющие скобки только если ты точно знаешь зачем ты это делаешь. В противном случае лучше не ставить, ибо если ты все равно не понимаешь эффекта, то лучше пусть они не мешают.

2024-03-15 13:07 UTC, DimaTrushin commented on src/application.cpp
> +    render_window_.draw(&image[0], image.size(), sf::PrimitiveType::Points);
Почему вызов не имеет вид
```cpp
render_window_.draw(image, sf::PrimitiveType::Points);
```
?? Почему вдруг я тут на высоком уровне при вызове метода draw должен копаться в кишках image, чтобы его отрисовать? Почему метод draw не принимает объект целиком и сам не решает, что с ним делать? Это нарушение уровня абстракции.

2024-03-15 13:07 UTC, DimaTrushin commented on src/application.cpp
> +    while (render_window_.pollEvent(event)) {
Это же busy wait? Если так, то надо будет подумать о том, чтобы не крутиться в этом цикле до сожженого процессора.

2024-03-15 13:07 UTC, DimaTrushin commented on src/application.cpp
> +    drawFrame();
По идее этого метода тут быть не должно. У тебя картинка должна тоже прилетать по сигналу из ядра. То есть она отрисовывается, как только рендерер ее отрисовал и отправил ее во view. То есть весь рабочий код должен быть внутри цикла. А внешний контур в этой функции должен быть без конкретики.

2024-03-15 13:07 UTC, DimaTrushin commented on src/camera.cpp
> +               -1 - k_eps <= point.y() && point.y() <= 1 + k_eps &&
Заверни проверяемое условие в функцию с нормальным названием.

2024-03-15 13:07 UTC, DimaTrushin commented on src/camera.h
> +    Eigen::Matrix4d constructTransformMatrix();
Не используй сырые типы. Заведи юзинги, можешь глобальный хедер сделать и включать не Eigen напрямую, а прокси хедер, где твои using-ги введены. Например добавь using Matrix4 = Eigen::Matrix4d; Тебе даже не обязательно d использовать в названии, просто размер матрицы указать и все. А какой именно тип уже определяет using.

2024-03-15 13:07 UTC, DimaTrushin commented on src/geometry.cpp
> +Point2d get2dPoint(const Point3d& X) {
В Eigen есть функция обрезающая вектор с головы называется head и с хвоста, называется tail.

2024-03-15 13:07 UTC, DimaTrushin commented on src/geometry.h
> +using TransformMatrix = Eigen::Matrix4d;
Не делай специальный тип для переменной. То есть у тебя есть тип именно матриц размера 4 на 4, а для чего эта матрица используется это уже не важно, за это будет отвечать имя переменной. Скажем для подсчета элементов ты используешь size_t, и не надо городить number_of_variables, number_of_triangles и прочие псевдонимы для size_t, это не дает тебе никакого дополнительного смысла и только путает. Последние два названия хорошо подходят для имени переменных, а тип у них у всех один, ты и то и другое считаешь в штуках. Так же и тут с матрицами, нет смысла заводить TransformMatrix тип, тип у тебя Matrix4. А если в переменной ты хранишь матрицу преобразования, то так называешь переменную, а не тип.

2024-03-15 13:07 UTC, DimaTrushin commented on src/geometry.h
> +constexpr double k_eps = 1e-9;
Глобальные константы лучше снабжать префиксом g_. Ну потому что только дегенерат делает не константными глобальные данные и не заворачивает их в синглтон. А так у тебя будет возможность в коде понять, что это глобальная константа, а не просто локальная.

2024-03-15 13:07 UTC, DimaTrushin commented on src/geometry.h
> +    void operator+=(const Point3d& shift);
Две веши:
1) Для структур делай все операторы и функции внешними. Им не надо быть членами структуры, потому что доступ ко всем полям все равно есть даже снаружи.
2) Не нарушай сигнатуру операторов. Ожидается, что операторы вида += возвращают ссылку на *this.

2024-03-15 13:07 UTC, DimaTrushin commented on src/object.cpp
> +Object::Object(std::vector<Triangle> triangles, const Point3d& position)
Я бы наверное ожидал в будущем не просто position, а еще версию конструктора, где второй аргумент матрица преобразования, то есть ты сдвигаешь в position локальное начало координат для треугольников, и потом еще применяешь матрицу поворота или вообще невырожденное линейное преобразование.

2024-03-15 13:07 UTC, DimaTrushin commented on src/object.cpp
> +Object::Object(std::vector<Triangle> triangles, const Point3d& position)
А почему не по rvalue reference? У тебя есть ситуация, когда ты хочешь с помощью этого метода построить объект и скопировать данные? Или ты всегда их будешь воровать? Если всегда воровать, то лучше сделать std::vector<Triangle>&&, тогда ты просто не сможешь использовать конструктор в случае, когда надо сделать копию. Ну или как я предлагал в другом комментарии закрыть копирование у вектора везде, где надо.

2024-03-15 13:07 UTC, DimaTrushin commented on src/renderer.h
> +    ZBuffer zBufferAlgorithm(const Camera& camera, const World& world);
У этой функции нет глагола в названии. Что она делает? Всегда должен быть один и только один глагол в начале названия любой функции. Исключениями могут быть методы доступа к приватным полям класса только для чтения, чтобы не писать get_value() или что-то в этом духе, можено писать value(). Но в большинстве случаев плохая идея не снабжать функцию глаголом. Потому что именно код функций выполняет работу на процессоре. Хорошо бы понимать, что это за работа.

2024-03-15 13:07 UTC, DimaTrushin commented on src/renderer.h
> +        double depth = 1;
Магическая константа.

2024-03-15 13:07 UTC, DimaTrushin commented on src/renderer.h
> +        sf::Color color = sf::Color::Black;
Это тоже другая форма магической константы. Тут можно было бы написать BackgroundColor и вот он уже имеет значение Black.

2024-03-15 13:07 UTC, DimaTrushin commented on src/renderer.h
> +                           Renderer::ZBuffer& z_buffer_);
1) Не делай квалификатор доступа для типа внутри Renderer. Ты можешь тут просто написать ZBuffer, это будет более читаемо.
2) Не делай название локальной переменной с подчеркиванием. Суть этого подчеркивания, чтобы отличать поля класса от локальных переменных.
3) Если уж ты приватную переменную передаешь явно, то стоит сделать метод static. Просто если ты часть полей класса передаешь явно, часть неявно через this, то это смешение стилей. Либо уж все данные передавай явно, либо ничего не передавай.
4) Ну и странно, что у тебя ничего никуда не возвращается.

2024-03-15 13:07 UTC, DimaTrushin commented on src/settings.h
> +static constexpr double k_fov_angle = M_PI / 2;
1) Макрос M_PI не работает без специального дефайна
```cpp
#define _USE_MATH_DEFINES // for C++
#include <cmath>
```
Потому что это нестандартное расширение языка. Но ты же пользуешься C++20, у него есть
```cpp
#include <numbers>
constexpr double g_fov_angle = std::numbers::pi / 2.;
```
2) УБЕРИ static отсюда! Во-первых, в случае constexpr, static просто ничего не делает (точнее у тебя все равно будет internal linkage, то есть в каждой единице трансляции будет своя копия этой переменной), а потому не надо лишних слов. Уж лучше inline тогда написать. Тогда гарантируется, что будет external linkage и эта переменная не будет дублироваться у линкера в каждой единице трансляции со своим новым именем.

2024-03-15 13:07 UTC, DimaTrushin commented on src/world.cpp
> +void World::addObject(const Object& object) {
А почему нет версии с Object&&, чтобы мувнуить объект? Ты вряд ли хочешь просто так скопировать и удалить внешний объект. Ты скорее всего хочешь своровать внутренности.

2024-03-15 13:07 UTC, DimaTrushin commented on src/world.cpp
> +            triangles.emplace_back(std::move(triangle));
Ну вот это полная глупость. У тебя const reference и ты пытаешься ее кастануть к rvalue, получается const Triangle&& и так как это const объект, то вместо move конструктора выбирается copy конструктор. Запомни, move и const не совместимы по физическому смыслу. Потому когда ты их пишешь рядом, то что-то делаешь не так. У тебя тут везде копии. И emplace_back тут ничем не отличается от push_back, потому что ты передаешь не аргументы конструктора, а целиком объект.

2024-04-09 14:21 UTC, K1ngNothing commented on src/application.cpp
> +    while (render_window_.pollEvent(event)) {
Это временный костыль. Потом я добавлю обработку клавиш пользователя и тогда это будет иметь больше смысла. А так прямо сейчас убрать while нельзя, т.к. иначе операционка подумает, что окно не отвечает и что его нужно закрыть.

EDIT: добавил простую обработку нажатий клавиш, при которой я просто каждый кадр смотрю на нажатые клавиши. Т.е. проблема с соженным процессором все еще есть, но сейчас она смягчена ограничением на частоту кадров.

2024-04-09 14:21 UTC, K1ngNothing commented on src/application.cpp
> +    render_window_.draw(&image[0], image.size(), sf::PrimitiveType::Points);
Потому что так SFML работает... Видимо стоит попробовать добавить метод в класс sf::RenderWindow, как ты предлагал сделать с sf::Color для умножения цвета на константу.

2024-04-09 14:21 UTC, K1ngNothing commented on src/renderer.h
> +                           Renderer::ZBuffer& z_buffer_);
1, 2, 3: Это я просто насрал пока перебирал возможные дизайны в рендере, my bad. `z_buffer_` все же локальная переменная и суффикс здесь ошибочный.

4: Чет не очевидно, а что тут возвращать. Идея метода: добавить треугольник в `z_buffer`. Хочется, чтобы `z_buffer` принимался по неконстантной ссылке, т.к. я а) не хочу копирования б) хочу менять объект. Но тогда нет смысла что-то возвращать, т.к. `z_buffer` и так уже поменялся. Возможно стоит переименовать метод в что-то вроде `addTriangleToZBuffer`, и тогда код станет более читаемым.

2024-04-09 14:21 UTC, K1ngNothing commented on src/settings.h
> +static constexpr double k_fov_angle = M_PI / 2;
1. Классно, не знал про `std::numbers`
2. Это наследие выноса из класса, и смысл static-а был не в настройке линковки, а в том, чтобы избежать создание переменной в классе (хотя не уверен, что это необходимо с учетом constexpr, но вроде clangd мне на это ругался). Здесь офк это не имеет смылса, т.к. переменная глобальная. Так что пофикшу.

2024-04-09 14:21 UTC, K1ngNothing commented on src/world.cpp
> +            triangles.emplace_back(std::move(triangle));
Да, тут я смачно насрал кншн) Подозреваю, что раньше `triangle` все же был типа `Triangle&`, но в какой-то момент я бахнул const и теперь здесь написан треш. Про `emplace_back` vs `push_back` принял к сведению, действительно здесь следует использовать `push_back`

2024-04-09 14:21 UTC, K1ngNothing commented on src/renderer.cpp
> +            sf::Vector2f position{static_cast<float>(i), static_cast<float>(screen_h - j)};
3. Здесь float нужен исключительно из-за интерфейса SFML: там позиция пикселя на экране задается как sf::Vector2f, из-за чего интовые координаты приходится кастовать к float. Никакого отношения к моей дабловой системе координат это не имеет.

2024-04-09 14:21 UTC, K1ngNothing commented on src/object.cpp
> +Object::Object(std::vector<Triangle> triangles, const Point3d& position)
Да, в будущем нужно сделать матрицу. Просто сейчас это как будто не имеет большого смысла, т.к. я не разрешаю пользователю двигать объекты во время работы приложения. А в текущем формате, где я сначала создаю сцену, и потом разрешаю пользователю по ней двигаться, вращение объекта большого смысла не имеет: пользователь так и так сможет рассмотреть объект со всех сторон.

2024-04-09 14:21 UTC, K1ngNothing commented on src/renderer.h
> +        sf::Color color = sf::Color::Black;
Чет я не справился по-нормальному сделать константу для цвета, подробнее напишу в комментарии к текущей версии кода.

2024-04-09 14:21 UTC, K1ngNothing commented on src/application.cpp
> +    while (render_window_.isOpen()) {
На данный момент приложение работает не на ивентах (как скорее всего было бы правильно сделать), а на том, что я каждый кадр проверяю, какие кнопки нажимает пользователь.

2024-04-09 14:21 UTC, K1ngNothing commented on src/application.cpp
> +    while (render_window_.pollEvent(event)) {
Вот это чудо следовало бы переделать, потому что оно противоречит логике работы Application::Run(). Но я пока оставил так, потому что а) это с виду работает б) по-хорошему управление надо было бы написать на ивентах, и тогда то, что я здесь делаю, будет норм.

2024-04-09 14:21 UTC, K1ngNothing commented on src/world.h
> +private:
Мб стоило сделать отдельный контейнер для треугольников, и вынести итераторы туда. Но по крайней мере сейчас у мира больше нет никаких задач, кроме как хранить треугольники, так что пока сделал так.

2024-05-06 15:32 UTC, K1ngNothing commented on src/scenes.h
Мне не оч нравится, как это сейчас сделано. Как будто стоило бы выкинуть scenes.* из src на уровень выше, т.к. они не связаны с приложением напрямую. С другой стороны, я планирую это все выпилить, когда разберусь в obj файлами, так что пока не стал париться.

2024-05-06 15:34 UTC, K1ngNothing commented on docs/svg/Class_Diagram.svg
Диаграмма устарела, надо будет обновить

2024-05-06 19:42 UTC, DimaTrushin requested changes
Обрати внимание, что я не повторял замечания. Если одна и та же ошибка всречалась несколько раз, я комментировал лишь единожды. Потому я ожидаю, что ты поправишь все аналогичные замечания всюду.

В целом архитектура application нормальная. У меня там есть небольшие замечания, а так у тебя получился run-time loop.

Ничего критичного не вижу в коде. Есть кучаразных мелочей, на которые постарался обратить внимание.

2024-05-06 19:42 UTC, DimaTrushin commented on src/application.h
> +    void createScene();
Меня всегда радуют методы без аргументов и не возвращающие ничего. Они всегда скрывают поток данных и просто манипулируют "глобальным" состоянием (в данном случае состояием объекта).

2024-05-06 19:42 UTC, DimaTrushin commented on src/application.h
> +    sf::RenderWindow render_window_;
Не используй обращение к классам через квалификатор пространства имен. Лучше в таких случаях заводить using-ги в начале класса в приватной его части, чтобы не таскать длинные имена. Тут это не так критично, но это моет сильно облегчить чтение кода.

2024-05-06 19:42 UTC, DimaTrushin commented on src/application.cpp
> +    render_window_.setFramerateLimit(settings::k_framerate_limit);
Если хочешь сделать настройки динамическими, то можно хранить структуру с настройками внутри приложения. Обычно делают даже так. Ты принимаешь settings по observer порту и обновляешь нужные состояния при изменении параметров. Но такой подход тоже хорошо работает в этом случае. Это чисто так, слова на размышления.

2024-05-06 19:42 UTC, DimaTrushin commented on src/application.cpp
> +    createScene();
Это нормальное использование функции без параметров и не возвращающей результаты.

2024-05-06 19:42 UTC, DimaTrushin commented on src/application.cpp
> +        checkWindowClosing();
У тебя нарушен стиль. У тебя первые две строчки 20 и 21 явно передают аргументы, а потом последние две строчки 22 и 23 неявно что-то делают с глобальным состоянием.

2024-05-06 19:42 UTC, DimaTrushin commented on src/application.cpp
> +        FrameMovement camera_movement = getUserInputs(delta_time);
Плохое название метода. Название метода getUserInput, а справа стоит camera_movement. И еще совсем не понятно зачем тут нужно delta_time. Судя по всему ты в этом методе делаешь несколько разных вещей:
1) считываешь ввод
2) определяешь из него что надо сделать с камерой
3) вычисляешь на сколько именно надо подвинуть камеру в зависимости от пройденного времени
Хорошо бы разделить эти задачи, потому что сейчас у тебя название метода врет. Тебе надо знать имя переменной camera_movement, чтобы понять, что она возвращает.

2024-05-06 19:42 UTC, DimaTrushin commented on src/application.cpp
> +    world_.addObject(std::move(createObamaPyramid(world_)));
Лишний std::move. У тебя createObamaPyramid возвращает временный объект, который и так является rvalue, потому у тебя и так будет вызван мув. Тебе не надо тут писать дополнительный каст, он лишь уменьшает читаемость кода.

2024-05-06 19:42 UTC, DimaTrushin commented on src/application.cpp
> +    world_.addObject(std::move(createObamaPyramid(world_)));
Очень странный api. Какого хрена у тебя функция создания пирамиды принимает world_??? Если я правильно понимаю это надо для внедрения в глобальную систему координат, но это должен делать метод добавляющий объект.

2024-05-06 19:42 UTC, DimaTrushin commented on src/application.cpp
> +    while (render_window_.isOpen()) {
Это тоже рабочий подход. Это называется run-time loop. Важно не смешивать разные подходы.

2024-05-06 19:42 UTC, DimaTrushin commented on src/application.cpp
> +void Application::checkWindowClosing() {
Плохое название. Эта функция не просто проверяет закрывается ли окно. Оно проверяет событие на закрытие и закрывает окно. Нужно название другое вроде closeWindowIfClosing (это я от балды придума, просто надо названием отразить что тут происходит).

2024-05-06 19:42 UTC, DimaTrushin commented on src/application.cpp
> +FrameMovement Application::getUserInputs(double delta_time) {
Во-первых, метод должен быть const.
Во-вторых, я бы назвал getCameraMovementFromKeyboard();
В-третьих, я бы убрал delta_time отсюад и возвращал бы все в каких-то дефолтных единицах измерения скажем в секунду. А потом бы умножал бы это на пройденное время снаружи от этой функции. Чтобы разделить роли, потому что тут время вообще ни к селу ни к городу в этом методе.

2024-05-06 19:42 UTC, DimaTrushin commented on src/application.cpp
> +    double turning_val = settings::k_camera_turning_speed * delta_time;
Используй эти константы без времени, а потом просто добавь оператор *= и умножай на время после возвращения этой структуры.

2024-05-06 19:42 UTC, DimaTrushin commented on src/application.cpp
> +    // movement
наличие комментария означает, что ты не выделил тут функцию. Ты по сути мог написать
```cpp
Point3 shift = getCameraShiftFromKeyboard();
double turn_up = getCameraTurnUpFromKeyboard();
...
return FrameMovement{
        .shift = shift,
        .turn_up = turn_up,
        .turn_right = turn_right,
        .turn_clockwise = turn_clockwise};
```

Еще замечание, у этих углов есть стандартные названия roll pitch yaw  https://www.muhendisbeyinler.net/roll-pitch-yaw-nedir/

2024-05-06 19:42 UTC, DimaTrushin commented on src/application.cpp
> +void Application::drawFrame() {
Эта функция опять врет. Она не рисует фрейм, она еще и создает картинку для фрейма. Я бы вынес строчку 96 наружу в метод run, а потом бы сделал метод
```cpp
void draw(const mage& image);
```
и тогда у тебя будет понятно, откуда взялся фрейм, кто его создал и кто его отрисовал.
И вот внутри draw уже две строчки 97 и 98.

2024-05-06 19:42 UTC, DimaTrushin commented on src/application.cpp
> +    render_window_.draw(&image[0], image.size(), sf::PrimitiveType::Points);
Можно просто завернуть именно этот вызов и следующую строчку в метод draw. Этого достаточно.

2024-05-06 19:42 UTC, DimaTrushin commented on src/application.cpp
> +        drawFrame();
Я бы изменил код так (посмотри все остальные комментарии)
```cpp
double delta_time = frame_clock.restart().asSeconds();
FrameMovement camera_movement = readCameraMovementFromKeyboard();
camera_movement *= delta_time;
camera_.moveCamera(camera_movement);
Image image = renderer_.renderImage(camera_, world_);
draw(image);
closeWindowIfClosing();
```
Так будет лучше видно поток данных, он не спрятан за манипулирование состоянием application с помощью методов без аргументов.

2024-05-06 19:42 UTC, DimaTrushin commented on src/application.h
В целом я не вижу проблемы с тем, как организован application. Это обычный run-time loop. Я просто сделал чуть более явным поток данных и местами изменил структурирование кода.

2024-05-06 19:42 UTC, DimaTrushin commented on src/frame_movement.h
> +inline FrameMovement operator-(const FrameMovement& movement) {
Добавь inplace операторы +=, -= и *=. Как минимум умножение тебе пригодится, чтобы нормировать по времени.

2024-05-06 19:42 UTC, DimaTrushin commented on src/frame_movement.h
> +inline FrameMovement operator-(const FrameMovement& movement) {
Почему имплементация в хедере? Ты естировал и уперся в производительность? А если уперся, то почему нет inplace операций? А если не тестировал, то зачем не вынес в cpp файл?

2024-05-06 19:42 UTC, DimaTrushin commented on src/frame_movement.h
> +inline Matrix4 translateMovementToMatrix(const FrameMovement& movement) {
Почему не в cpp?

2024-05-06 19:42 UTC, DimaTrushin commented on src/world.h
> +        const World& world_ref_;
Не храни никогда ссылки в классе, ты ломаешь value semantics. Твой класс становится не переприсваеваемым. Вместо этого храни std::reference_wrapper. Это то же самое что хранить указатель (то есть у тебя соблюдается value semantics) но при этом у тебя гарантируется, что этот указатель не нулевой.

2024-05-06 19:42 UTC, DimaTrushin commented on src/world.h
> +    Triangles(const World& world_ref);
не надо добавлять _ref в название переменной. Вообще старайся не связывать название переменной с имплементацией. Старайся в название отражать использование. Потому что ссылка это или прокси объект или указатель, это все может поменяться тысячу раз. Потому просто world и все.

2024-05-06 19:42 UTC, DimaTrushin commented on src/world.h
> +
добавсь еще operator->() const для красоты, мое чувство прекрасного умирает.

2024-05-06 19:42 UTC, DimaTrushin commented on src/world.h
> +    const sf::Image* loadTextureFromFile(const std::string filename);
Вот этот метод выглядит максимально странным.
1) Во-первых, он подразумевает, что world должен уметь работать с файлами
2) Во-вторых, вместо std::system::path используется std::string
3) В-третьих, возвращаемое знчение -- указатель, КАРЛ! Кто владеет возращаемым значением не понятно.

2024-05-06 19:42 UTC, DimaTrushin commented on src/world.h
> +    Triangles getTriangles() const;
убери get из названия. Старайся делать get только для методов, которые получают доступ к данным, которые где-то хранятся, а тут это просто Triangles(). Ну или если ты хочешь явно сказатЬ, что ты что-то строишь, то можно добавить create или make в названии в начале.

2024-05-06 19:42 UTC, DimaTrushin commented on src/world.h
> +    std::vector<Object> objects;
А зачем ты хранишь вектор объектов, а не вектор треугольников? Потому что так у тебя получается вектор векторов из треугольников. В этом есть какой-то сокровенный смысл или это ошибка дизайна?

2024-05-06 19:42 UTC, DimaTrushin commented on src/world.cpp
> +    objects.push_back(object);
Поменяй местами 58 и 59 и потом вместо 58 напиши
```cpp
objects.push_back(std::move(object));
```
Не забывай, что rvalue reference не проталкивается сквозь вызовы, надо руками ее прописывать каждый раз. Просто в этом месте ты можешь сделать линшюю копию, которую не ожидаешь.

2024-05-06 19:42 UTC, DimaTrushin commented on src/world.cpp
> +    auto it = textures_.find(filename);
Охренеть, ты текстуры по именам файлов идентифицируешь. Так лучше не делать. Заведи отдельный id по которому ты будешь отличать текстуры и присваивай его.

2024-05-06 19:42 UTC, DimaTrushin commented on src/world.cpp
> +            "TextureManager::loadFromFile: invalid filename");
Уверен, что ты хочешь завалить программу из-за того, что ты не смог прочитать текстуру из файла? Я бы лучше возвращал в этом случае nullptr и пусть пользователь этой функции проверяет, что текстура есть. Все таки она же не всегда может найтись. Мало ли какую текстуру я запрошу.
Но в целом, если такой дизайн, что все захардкожено и ты реально хочешь тут упасть, то ОК.

2024-05-06 19:42 UTC, DimaTrushin commented on src/world.cpp
> +const sf::Image* World::loadTextureFromFile(const std::string filename) {
Ты смешал две разные функции тут. У тебя есть задача скачать текстуры из файла и задача получить доступ к текстуре, которая уже хранится. Ты тут делаешь обе эти задачи сразу. Так бывает надо, но тут у тебя список текстур заранее известен, что мешало загрузить все текстуры в конструкторе (например в конструкторе application, потому что ты уже там грузишь объекты и будет не хорошо объекты грузить там, а текстуры в конструкторе world), а потом же сделать метод доступа к текстурам по id-шнику среди тех, которые хранятся. И у тебя в итоге будут разделены задачи методов. И более того, ктогда можно исключить отсюда метод чтения из файла, он будет уже методом другого объекта, который умеет читать из файла или метод application, а здесь лишь надо иметь метод добавления текстуры и присвоения ей id-шника (не делай его именем файла) и потом метод доступа по id-шнику. И этот метод должен уметь сфейлиться, то есть вернуть nullptr, если текстуры нет.

2024-05-06 19:42 UTC, DimaTrushin commented on src/vertex_attributes.h
> +    sf::Color getColor() const;
Нахуя, а главное зачем? Зачем метод в структуре, да еще и тот, который может сфейлиться? Если вместо attr.getColor() ты можешь написать *attr.color? Второе еще и более читаемое. Потому что мы знаем, что доступ чез * может сфейлиться и это может намекнуть нам, что надо для начала сделать какую-то проверку.
UPD я посмотрел, что происходит. И возник вопрос, а почему не std::variant<sf::Color, TextureCoords>? Ты же как раз хочешь хранить или то или то и в зависимости от этого уже принимать решения?

2024-05-06 19:42 UTC, DimaTrushin commented on src/texture_coords.h
> +        .y = static_cast<size_t>(tcoords.y * t),
Вот эти касты означают, что ты делаешь преобразование системы координат, но вместо того, чтобы посвятить этому отдельную функцию, ты все смешал воедино. Ты в этой функции не только умножаешь на число координаты, а ты еще делаешь преобразование системы координат.

2024-05-06 19:42 UTC, DimaTrushin commented on src/texture_coords.h
> +inline TextureCoords operator+(
Плохая сигнатура. Во-первых, я не понимаю, почему метод не inplace, то есть operator+=. Во-вторых, у тебя не корректно складывать TextureCoordinates, потому что они еще хранят текстуру, корректно прибавить что-то вроде point2, которая измеряется в size_t. Это как арфиметика с указателями. Разность двух указателей не указатель и имеет другой тип, на который можно сдвигать указатель. Подумай про это.

2024-05-06 19:42 UTC, DimaTrushin commented on src/renderer.h
> +using Image = std::vector<sf::Vertex>;
Тебе точно достаточно такого голого контейнера? Не нужно ли завернуть в Eigen::Array или Container2D?

2024-05-06 19:42 UTC, DimaTrushin commented on src/renderer.h
> +        sf::Color color = sf::Color::Black;  // background color
вместо комментария назови переменную backgroud_color.

2024-05-06 19:42 UTC, DimaTrushin commented on src/renderer.cpp
> +struct PixelCoords {
Такое ощущение, что у тебя много где не хватает этой сущности.

2024-05-06 19:42 UTC, DimaTrushin commented on src/renderer.cpp
> +        discretize(raw_y, settings::k_window_h),
Не очень хоршо иметь такие глобальные зависимости. Но пусть так остается, у тебя по дизайну настройки глобальные.

2024-05-06 19:42 UTC, DimaTrushin commented on src/renderer.cpp
> +std::vector<HTriangle> Renderer::getHTriangles(
Я так понимаю, тут у тебя тоже не get, а create.

2024-05-06 19:42 UTC, DimaTrushin commented on src/renderer.cpp
> +    return createImage(constructZBuffer(getHTriangles(camera, world)));
немного странно выглядит, что ты по треугольникам (с доп информацией) строиш z буффер, а потом из него картинку. Я бы ожидал, что картинка строится с помощью буффер из треуголников. В итоге возникает вопрос, у тебя z буффер помнит все треугольники? Это очень интересный буффер. Как минимум очень умный и памятливый.

2024-05-06 19:42 UTC, DimaTrushin commented on src/renderer.cpp
> +void Renderer::addHTriangleToZBuffer(
Вот это очень похоже на растеризацию треугольника. Потому я не понимаю, почему этот метод так называется.

2024-05-06 19:42 UTC, DimaTrushin commented on src/hvertex.h
> +    double z_reciprocal_;
А это что за хрень?

2024-05-06 19:42 UTC, DimaTrushin commented on src/hvertex.cpp
> +    if (h_vertices_[0].hPosition().y() < h_vertices_[1].hPosition().y()) {
Отлично отсортировал =) хоть бы выделил это в метод под названием sortByYCoordinate

2024-05-06 19:42 UTC, DimaTrushin commented on src/geometry.h
> +enum Side {
1) Никогда НЕ испльзуй enum, потому что он замусоивает пространство имен. Все эти имена внутри Side утекают в окружающее пространство имен render_app. Вместо этого используй enum class.
2) Никогда не используй CAPS_ONLY стиль ни для чего кроме макросов. Потому что это будет сбивать с толку программистов читающих твой код. Они будут ожидат, что это макросы.
3) Если тебе нужны константы, которые ты не хочешь кастовать, то ты можешь сделать constexpr переменные статические внутри структуры или внутри пространства имен. Но если ты все таких хочешь исползовать enum, то можно сделать так
```cpp
struct Side {
enum : char {
  Inner = 1, Outer = -1
};
};
```
Тогда имена утекут только внутрь структуры Side. Но в этом случае не понятно чем это лучше, чем static constexpr переменные.

2024-05-06 19:42 UTC, DimaTrushin commented on src/container2d.h
> +    size_t cols_;
достаточно хранить только один из этих размеров. Потому что  ты можешь восстановить другой размер через размер вектора.

2024-05-06 19:42 UTC, DimaTrushin commented on src/camera.h
> +    Triangle moveTriangle(const Triangle& triangle) const;
непонятный метод. Как минимум из названия не ясно, Что он делает.

2024-05-06 19:42 UTC, DimaTrushin commented on src/camera.cpp
> +            "Triangle clipping failed: inadequate vertex count");
А зачем кидать ошибку в рантайме? Почему ассерта не достаточно?

2024-05-06 19:42 UTC, DimaTrushin commented on src/camera.cpp
> +Triangle Camera::moveTriangle(const Triangle& triangle) const {
то есть это transformTriangle

2024-05-06 19:42 UTC, DimaTrushin commented on src/camera.cpp
> +    movement_mat_ = translateMovementToMatrix(-movement) * movement_mat_;
А матрица transform_mat_ и clipping_planes_ они в локальных координатах? Их не надо двигать?

2024-05-06 19:42 UTC, DimaTrushin commented on src/vertex_attributes.h
> +    throw std::runtime_error("VertexAttributes::getColor: no color available");
почему не assert?

2024-09-28 00:41 UTC, K1ngNothing commented on src/camera.cpp
> +    movement_mat_ = translateMovementToMatrix(-movement) * movement_mat_;
Да, у меня сделано так, что камера статичная, а объекты двигаются вокруг нее. Сейчас пока пишу я задумался, а нахуй я так сделал, но что есть, то есть.

2024-09-28 00:41 UTC, K1ngNothing commented on src/camera.cpp
> +Triangle Camera::moveTriangle(const Triangle& triangle) const {
Нет, потому что я трансформирую вершины треугольника, используя матрицу сдвига. Скорее всего нужен или лучший нейминг для метода transformPoint из geometry.h, или как-то по-другому называть методы в Camera, потому что сейчас реально запутывает.

2024-09-28 00:41 UTC, K1ngNothing commented on src/camera.cpp
> +            "Triangle clipping failed: inadequate vertex count");
Потому что из-за дерьмовой производительности в дебаге я тестировал рендер в релизе, и весело просрал данный ассерт) Но вообще конечно да, нужно оставить только ассерт.

2024-09-28 00:41 UTC, K1ngNothing commented on src/renderer.h
> +using Image = std::vector<sf::Vertex>;
А зачем? SFML хочет получить список пикселей для отрисовки, в каждом пикселе уже записаны его координаты.

2024-09-28 00:41 UTC, K1ngNothing commented on src/vertex_attributes.h
> +    sf::Color getColor() const;
Вообще пока я это писал я думал над общей архитектурой, где помимо этих атрибутов могут быть и другие (те же нормали например), поэтому и хотел использовать набор optional + метод getColor(), который эти optional-ы парсит. Про std::variant: я подумал, что можно сделать смешивание цвета из текстуры и базового цвета треугольника. Хз, насколько это разумно + не тестировал как это выглядит на практике, но как потенциальную возможность оставил.

2024-09-28 00:41 UTC, K1ngNothing commented on src/application.cpp
> +    world_.addObject(std::move(createObamaPyramid(world_)));
Нет, world_ нужен в первую очередь для загрузки текстур. Но вообще надо будет подумать про то, чтобы переделать работу с текстурами.

2024-09-28 00:41 UTC, K1ngNothing commented on src/frame_movement.h
> +inline FrameMovement operator-(const FrameMovement& movement) {
Нет, никаких умных мыслей у меня здесь не было, просто было впадлу + изначально предполагал, что будут короткие методы без сложной логики. Вообще надо будет поресерчить, какие трейдофы есть у inline в хэдере и дефолтного способа с cpp, а то пока вообще не в курсе в чем разница.

EDIT: как будто бы разницы толком и нет..? Тип компилятор при желании так и так может заинлайнить функцию (или наоборот сделать полноценный вызов). С inline ему это сделать будет проще, т.к. не надо будет лезть в другие единицы трансляции, но вот почему inline может быть неоч я чет сходу не понял.

2024-09-28 00:41 UTC, K1ngNothing commented on src/frame_movement.h
> +inline FrameMovement operator-(const FrameMovement& movement) {
А зачем += и -= ...? Просто для красоты?

2024-09-28 00:41 UTC, K1ngNothing commented on src/hvertex.h
> +    double z_reciprocal_;
Обратная величина к оригинальной z-координате, писал в отчете

2024-09-28 00:41 UTC, K1ngNothing commented on src/renderer.h
> +        sf::Color color = sf::Color::Black;  // background color
Не хочу просто создавать переменную типа sf::Color, потому что тогда я с нихера увеличу размер структуры. В идеале я хотел бахнуть constexpr или хотя бы static const, но чет сходу не получилось, потом буду разбираться.

2024-09-28 00:41 UTC, K1ngNothing commented on src/world.h
> +    std::vector<Object> objects;
Смысл был в том, чтобы в случае чего можно было работать с объектами по отдельности (например, удалить объект из сцены). Сейчас это не используется, но глобально как будто имеет смысл.

2024-09-28 00:41 UTC, K1ngNothing commented on src/world.cpp
> +const sf::Image* World::loadTextureFromFile(const std::string filename) {
Соглы, что стоит разделить методы чтения текстуры из файла и обращения к текстуре по id. Но пока не хочу выносить метод чтения из файла из World куда-то наружу (например, в application). У меня была идея, что World ответственен за работу с объектами, а текстуры по факту являются частью объекта => не хочется раскидывать обязанности хрен пойми куда. Тем более у меня были смутные планы допиливать данный проект, и тогда мне понадобится добавлять и удалять текстуры по ходу работы приложения, а не только в самом начале.

2024-09-28 00:41 UTC, K1ngNothing commented on src/texture_coords.h
> +inline TextureCoords operator+(
1) Потому что этот метод используется в инетрполяции, поэтому там формула вида c = a * (1 - t) + b * t. Да, inplace было бы оптимальнее, но это бы ухудшило читаемость кода 2) Надо подумать в эту сторону, на данный момент я обложился ассертами и в методе, и в месте, где я его дергаю

2025-04-19 11:11 UTC, merged